language: java
sudo: false

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=IC-13.1.6

before_install:
 - chmod +x gradlew
 - pip install --user codecov
 - wget http://download.jetbrains.com/idea/ideaIC-13.1.6.tar.gz
 - mkdir ideaIC-13.1.6
 - tar -C ideaIC-13.1.6 --strip-components=1 -xzf ideaIC-13.1.6.tar.gz
 - zip -r ideaIC-13.1.6.zip ideaIC-13.1.6/*
 - wget http://download.jetbrains.com/idea/ideaIC-13.1.6-src.tar.bz2
 - mkdir ideaIC-13.1.6_src
 - tar -C ideaIC-13.1.6_src --strip-components=1 -xjf ideaIC-13.1.6-src.tar.bz2
 - zip -r ideaIC-13.1.6_src.zip ideaIC-13.1.6_src/*
 - mvn install:install-file -Dfile=ideaIC-13.1.6.zip -Dsources=ideaIC-13.1.6_src.zip -DgroupId=com.jetbrains.intellij.idea -DartifactId=ideaIC -Dversion=13.1.6 -Dpackaging=zip

after_success:
  - codecov