language: java
sudo: false

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=IU-13.1.6

before_install:
 - chmod +x gradlew
 - pip install --user codecov
 - wget http://download.jetbrains.com/idea/ideaIU-13.1.6.tar.gz
 - mkdir ideaIU-13.1.6
 - tar -C ideaIU-13.1.6 -xzvf ideaIU-13.1.6.tar.gz
 - zip -r ideaIU-13.1.6.zip ideaIU-13.1.6
 - mvn install:install-file -Dfile=ideaIU-13.1.6.zip -DgroupId=com.jetbrains.intellij.idea -DartifactId=ideaIU -Dversion=13.1.6 -Dpackaging=zip

after_success:
  - codecov